name: dotnet apply format

on:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      
    - name: Run dotnet format
      run: dotnet format --exclude **\MyPluginInfo.cs --exclude **\\MyPluginInfo.cs --exclude **/MyPluginInfo.cs

    - uses: stefanzweifel/git-auto-commit-action@v5
